# Generated by Django 4.1.7 on 2023-03-17 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Historia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrePaciente', models.CharField(max_length=50)),
                ('apellidoPaciente', models.CharField(max_length=50)),
                ('edadPaciente', models.IntegerField()),
                ('documento', models.IntegerField()),
                ('fechaNacimiento', models.DateField()),
                ('descripcion', models.TextField()),
            ],
        ),
    ]
